# Generated by Django 5.2.7 on 2025-10-10 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('reminder_time', models.TimeField()),
                ('notification_method', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('recurrence', models.CharField(choices=[('every_day', 'Every Day'), ('every_monday', 'Every Monday'), ('every_tuesday', 'Every Tuesday')], default='every_day', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
