# Generated by Django 5.2.7 on 2025-10-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_management', '0002_alter_medicinereminder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinereminder',
            name='last_sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicinereminder',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed')], default='processing', max_length=10),
        ),
    ]
