# Generated by Django 5.2.7 on 2025-10-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_management', '0003_medicinereminder_last_sent_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinereminder',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
