# Generated by Django 5.2.7 on 2025-10-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_management', '0004_medicinereminder_is_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinereminder',
            name='recurrence',
            field=models.CharField(choices=[('every_day', 'Every Day'), ('every_monday', 'Every Monday'), ('every_tuesday', 'Every Tuesday'), ('every_wednesday', 'Every Wednesday'), ('every_thursday', 'Every Thursday'), ('every_friday', 'Every Friday'), ('every_saturday', 'Every Saturday'), ('every_sunday', 'Every Sunday'), ('today', 'Today')], default='every_day', max_length=50),
        ),
    ]
