# Generated by Django 5.2.7 on 2025-10-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_management', '0005_alter_medicinereminder_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinereminder',
            name='notification_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='medicinereminder',
            name='notification_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
