# Generated by Django 5.2.7 on 2025-10-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_management', '0006_medicinereminder_notification_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinereminder',
            name='recurrence',
            field=models.CharField(choices=[('once_a_day', 'Once a day'), ('twice_a_day', 'Twice a day'), ('thrice_a_day', 'Thrice a day'), ('today', 'Today'), ('every_day', 'Every day'), ('every_monday', 'Every Monday'), ('every_tuesday', 'Every Tuesday'), ('every_wednesday', 'Every Wednesday'), ('every_thursday', 'Every Thursday'), ('every_friday', 'Every Friday'), ('every_saturday', 'Every Saturday'), ('every_sunday', 'Every Sunday')], default='every_day', max_length=50),
        ),
    ]
