# Generated by Django 5.2.7 on 2025-10-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_management', '0007_alter_medicinereminder_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinereminder',
            name='dose',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
