# Generated by Django 5.2.7 on 2025-10-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_management', '0008_medicinereminder_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinereminder',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
