# Generated by Django 5.2.7 on 2025-10-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_management', '0009_alter_medicinereminder_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinereminder',
            name='current_units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicinereminder',
            name='refill_choice',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicinereminder',
            name='reminder_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
