# Generated by Django 5.2.7 on 2025-10-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_management', '0010_medicinereminder_current_units_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinereminder',
            name='reminder_threshold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
